### ISSUE TITLE
Enable/disable tracks that were not enabled in initLocalTracks

### ISSUE THREAD

**Issue by SleepySquash** [instrumentisto/medea-jason#11]
## Background

Жизненный цикл звонка выглядит примерно следующим образом:
1. Инициализация локальных треков (`initLocalTracks`) и настроек (`setLocalMediaSettings`) от `MediaStreamSettings`, который при аудио звонке содержит только `audio` составляющую, а при видео звонке - `audio` и `deviceVideo`.
2. Нажатие на кнопку "выключить видео" вызывает `room.disableVideo(Device)` и в случае успеха удаляет и освобождает трек (и рендерер) этого видео. 
3. Нажатие на кнопку "включить видео" вызывает только лишь `room.enableVideo(Device)`, а сам трек приходит через `room.onLocalTrack` callback, откуда трек и добавляется. 
4. Пункты 2-3 описывают поведение и для аудио, и для screen sharing'а.

## Question

Если при инициализации локальных треков видео было включено, то описанное выше поведение работает идеально, видео включается и выключается, индикаторы гаснут и так далее. Однако если видео было выключено (т.е. отсутствовала при `initLocalTracks`/`setLocalMediaSettings` в `MediaStreamSettings` составляющая `deviceVideo`), то в таком случае `room.enableVideo(Device)` просто моментально выполняется (`await` моментален) без каких либо ошибок, при этом никакого enable'а не происходит. Аналогично и screen share, т.е. если вместо `Device` прокидывать `Display`. Отмечу, что если при инициализации локальных треков аудио было отключено, то `room.enableAudio` всё равно вызывает `onLocalTrack`, тем самым отрабатывая идеально даже при выключенном изначально аудио.
  
Вопрос: корректно ли я поступаю в данном случае? Судя по js демо, там используется примерно такая же логика. Хочется иметь возможность из аудио звонка перейти в видео звонок так, чтобы ни камера, ни шейринг экрана не включались при старте аудио звонка.  
  
И ещё вопрос, если можно: насколько некорректно дёргать заново `initLocalTracks` и `setLocalMediaSettings` для enable/disable камеры и шейринга экрана? Потому что если вызывать эти функции с включением или нет той или иной составляющей `deviceVideo` и `displayVideo`, то enable/disable отрабатывает идеально и как задумано. `audio` составляющая делает disable аудио, но `enable` аудио не отрабатывает таким образом.

**Comment by evdokimovs** [comment]
@SleepySquash ,

> Однако если видео было выключено (т.е. отсутствовала при initLocalTracks/setLocalMediaSettings в MediaStreamSettings составляющая deviceVideo), то в таком случае room.enableVideo(Device) просто моментально выполняется (await моментален) без каких либо ошибок, при этом никакого enable'а не происходит.

Да, это выглядит как странное поведение, и, возможно, нам стоит выкидывать ошибку в таких ситуациях. Хотя, в теории это можно рассматривать как частично корректное поведение, поскольку позволяет включить `Sender`'а до выбора constraints'ов для девайса, и в таком случае реальная отправка медиа начнется только после установки этих constraints. Но выглядит такой кейс маловероятно, и только усложняет API Jason'а.

> Вопрос: корректно ли я поступаю в данном случае? Судя по js демо, там используется примерно такая же логика. Хочется иметь возможность из аудио звонка перейти в видео звонок так, чтобы ни камера, ни шейринг экрана не включались при старте аудио звонка.

Я предполагаю, что Вы не обновляете constraints'ы перед включением медиа. В демке не очень очевидным образом происходит обновление constraints'ов в зависимости от включения/выключения медиа. [Вот строчка][1], которая решает какие constraints'ы подпихивать Jason'у в какой ситуации. То есть перед включением, допустим, веб-камеры, Вам нужно сделать `set_local_media_settings` с нужными `video` constraints'ами, и после этого включать видео для `Device`. Соответственно, при старте аудио звонка вы делаете `set_local_media_settings` только с аудио constraints'ами, а когда нужно включить видео, Вы добавляете `video` constraints, и включаете видео с помощью `enable_video`.

> насколько некорректно дёргать заново initLocalTracks и setLocalMediaSettings для enable/disable камеры и шейринга экрана?

С помощью `set_local_media_settings` Вы можете только выключать медиа, но не включать его. Это сделано для того, чтобы у пользователя оставалась возможность менять девайсы в тот момент, когда публикация выключена. Если сделать так, чтобы `set_local_media_settings` включал публикацию медиа, то любое изменение constraints'ов будет приводить к неожиданному включению публикации медиа.

> Потому что если вызывать эти функции с включением или нет той или иной составляющей deviceVideo и displayVideo, то enable/disable отрабатывает идеально и как задумано.

Вот самое забавное в этой ситуации то, что так не было задумано, и ничего включаться не должно. У меня в демо проектах так и не получилось воспроизвести ситуацию, когда видео включается с помощью `set_local_media_settings`. Возможно-ли, что у Вас в приложении как то неявно происходит включение видео при смене constraints'ов? И еще раз уточню, то есть если Вы в приложении сделаете последовательно что-то вроде:

1. `setLocalMediaSettings(/* video: null */)`
2. `setLocalMediaSettings(/* video: not null */)`

То у Вас включается видео? А если выключить видео с помощью `disableVideo`, и потом включить его с помощью `setLocalMediaSettings`, то оно включится?

[1]: https://github.com/instrumentisto/medea-jason/blob/4e7d81fd44d43eaa1f4fe386959b5ba41e82d563/e2e-demo/js/index.js#L463

**Comment by SleepySquash** [comment]
@evdokimovs, тысяча благодарностей за все объяснения. По enable видео: я действительно не вызывал `set_local_media_settings` перед enable видео, теперь всё отлично работает, спасибо ещё раз.

> Возможно-ли, что у Вас в приложении как то неявно происходит включение видео при смене constraints'ов?
Угу, так и есть, прошу прощения. При их изменении сразу вызывались `jason.media_manager().init_local_tracks(constraints)` вместе с `set_local_media_settings`, а из `init_local_tracks` я и брал треки. Мне почему-то казалось, что эти две функции строго связаны (и изменение настроек должно вызывать обе функции), но теперь я понимаю, что нет (и почему нет).
